### ISSUE TITLE
気球配置モードとボール投げモードを切り替えるボタンを物理ボタンとして用意する。

### ISSUE THREAD

**Issue by sgmtsnj** [nankatsukuritai/SiriBal#9]
- とりあえず気球配置 or ボール投げ の2モードで実装する
- ゲーム開始のところとか、点数表示のところとかは別のシーンにして切り替えたほうが良いので、この切替とは別で考える

**Comment by 5104** [comment]
おらがやるぞーっと

**Comment by 5104** [comment]
とりあえずボタン用意完了！
が、あと、クリック時にボール飛んでしまう。

ARモードでの動作未確認。
誰か見てくれ〜（笑）
